// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow that generates a risk disclaimer for the stock market.
 *
 * - generateRiskDisclaimer - A function that generates a risk disclaimer.
 * - GenerateRiskDisclaimerInput - The input type for the generateRiskDisclaimer function.
 * - GenerateRiskDisclaimerOutput - The return type for the generateRiskDisclaimer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRiskDisclaimerInputSchema = z.object({
  stockName: z.string().describe('The name of the stock.'),
});
export type GenerateRiskDisclaimerInput = z.infer<typeof GenerateRiskDisclaimerInputSchema>;

const GenerateRiskDisclaimerOutputSchema = z.object({
  disclaimer: z.string().describe('The generated risk disclaimer.'),
});
export type GenerateRiskDisclaimerOutput = z.infer<typeof GenerateRiskDisclaimerOutputSchema>;

export async function generateRiskDisclaimer(input: GenerateRiskDisclaimerInput): Promise<GenerateRiskDisclaimerOutput> {
  return generateRiskDisclaimerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRiskDisclaimerPrompt',
  input: {schema: GenerateRiskDisclaimerInputSchema},
  output: {schema: GenerateRiskDisclaimerOutputSchema},
  prompt: `You are an AI assistant that specializes in generating risk disclaimers for the stock market.

  Generate a disclaimer for the following stock: {{stockName}}.

  The disclaimer should be informative, concise, and easy to understand. It should highlight the risks and uncertainties involved in investing in the stock market.
  `,
});

const generateRiskDisclaimerFlow = ai.defineFlow(
  {
    name: 'generateRiskDisclaimerFlow',
    inputSchema: GenerateRiskDisclaimerInputSchema,
    outputSchema: GenerateRiskDisclaimerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
