
import type { NepseStockSymbol, BrokerInfo } from '@/types';

export const ALL_NEPSE_SYMBOLS: NepseStockSymbol[] = ["NABIL", "HDL", "UPPER", "API", "CIT"];

export const ALL_BROKERS: BrokerInfo[] = [
  { id: "B01", name: "Sweta Securities Pvt. Ltd. (1)", code: "1" },
  { id: "B03", name: "Arun Securities Pvt. Ltd. (3)", code: "3" },
  { id: "B04", name: "Opal Securities Investment Pvt. Ltd. (4)", code: "4" },
  { id: "B05", name: "Market Securities Exchange Pvt. Ltd. (5)", code: "5" },
  { id: "B06", name: "Agrawal Securities Pvt. Ltd. (6)", code: "6" },
  { id: "B07", name: "J.F. Securities Pvt. Ltd. (7)", code: "7" },
  { id: "B08", name: "Ashutosh Brokerage & Securities Pvt. Ltd. (8)", code: "8" },
  { id: "B10", name: "Pragyan Securities Pvt. Ltd. (10)", code: "10" },
  { id: "B11", name: "Malla & Malla Stock Broking Co. Pvt. Ltd. (11)", code: "11" },
  { id: "B13", name: "Floormsheet Pvt. Ltd. (13)", code: "13" },
  { id: "B14", name: "Nepal Stock House Pvt. Ltd. (14)", code: "14" },
  { id: "B16", name: "Purbanchal Securities Pvt. Ltd. (16)", code: "16" },
  { id: "B17", name: "ABC Securities Pvt. Ltd. (17)", code: "17" },
  { id: "B18", name: "Sagarmatha Securities Pvt. Ltd. (18)", code: "18" },
  { id: "B19", name: "Nepal Investment & Securities Pvt. Ltd. (19)", code: "19" },
  { id: "B20", name: "Sipla Securities Pvt. Ltd. (20)", code: "20" },
  { id: "B21", name: "Dynamic Money Managers Securities Pvt. Ltd. (21)", code: "21" },
  { id: "B22", name: "Siprabi Securities Pvt. Ltd. (22)", code: "22" },
  { id: "B25", name: "Swarnalaxmi Securities Pvt. Ltd. (25)", code: "25" },
  { id: "B26", name: "Asian Securities Pvt. Ltd. (26)", code: "26" },
  { id: "B28", name: "Shree Krishna Securities Ltd. (28)", code: "28" },
  { id: "B29", name: "Trishul Securities & Investment Ltd. (29)", code: "29" },
  { id: "B32", name: "Premier Securities Pvt. Ltd. (32)", code: "32" },
  { id: "B33", name: "Dakshinkali Investment Securities Pvt. Ltd. (33)", code: "33" },
  { id: "B34", name: "Vision Securities Pvt. Ltd. (34)", code: "34" },
  { id: "B35", name: "Kohinoor Investment & Securities Pvt. Ltd. (35)", code: "35" },
  { id: "B36", name: "Secured Securities Ltd. (36)", code: "36" },
  { id: "B37", name: "Oxford Securities Pvt. Ltd. (37)", code: "37" },
  { id: "B38", name: "Dipshikha Dhitopatra Karobar Co. Pvt. Ltd. (38)", code: "38" },
  { id: "B39", name: "Sumeru Securities Pvt. Ltd. (39)", code: "39" },
  { id: "B40", name: "Creative Securities Pvt. Ltd. (40)", code: "40" },
  { id: "B41", name: "Linch Stock Market Ltd. (41)", code: "41" },
  { id: "B42", name: "Sani Securities Co. Ltd. (42)", code: "42" },
  { id: "B43", name: "South Asian Bulls Pvt. Ltd. (43)", code: "43" },
  { id: "B44", name: "Dynamic Portfolio Management & Securities Pvt. Ltd. (44)", code: "44" },
  { id: "B45", name: "Naasa Securities Co. Ltd. (45)", code: "45" },
  { id: "B46", name: "Kalika Securities Pvt. Ltd. (46)", code: "46" },
  { id: "B47", name: "Neev Securities Pvt. Ltd. (47)", code: "47" },
  { id: "B49", name: "Online Securities Pvt. Ltd. (49)", code: "49" },
  { id: "B50", name: "Crystal Kanchenjunga Securities Pvt. Ltd. (50)", code: "50" },
  { id: "B51", name: "Oxford Securities Pvt. Ltd. (51)", code: "51" }, // Duplicate code, assuming typo or distinct entity, using as is.
  { id: "B52", name: "Sundhara Securities Ltd. (52)", code: "52" },
  { id: "B53", name: "Investment Management Nepal Pvt. Ltd. (53)", code: "53" },
  { id: "B54", name: "Sewa Securities Pvt. Ltd. (54)", code: "54" },
  { id: "B55", name: "Bhrikuti Stock Broking Co. Pvt. Ltd. (55)", code: "55" },
  { id: "B56", name: "Sri Hari Securities Pvt. Ltd. (56)", code: "56" },
  { id: "B57", name: "Aryatara Investment & Securities Pvt. Ltd. (57)", code: "57" },
  { id: "B58", name: "Imperial Securities Co. Pvt. Ltd. (58)", code: "58" },
  { id: "B59", name: "Deevyaa Securities & Stock House Pvt. Ltd. (59)", code: "59" },
  { id: "B60", name: "Capital Max Securities Pvt. Ltd. (60)", code: "60" },
  { id: "B61", name: " carretera capital limited (61)", code: "61" },
];
