// This file will be auto-generated by the Supabase CLI.
// Run `npm run gen-types:supabase` to generate it.
//
// It's good practice to have this file, even if it's initially empty or
// contains a placeholder, so your imports don't break before the
// first generation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Placeholder: Your table types will appear here after running the script
    }
    Views: {
      // Placeholder: Your view types will appear here
    }
    Functions: {
      // Placeholder: Your function types will appear here
    }
    Enums: {
      // Placeholder: Your enum types will appear here
    }
    CompositeTypes: {
      // Placeholder: Your composite types will appear here
    }
  }
}

// You can add a more specific type for your public schema if needed
// export type PublicSchema = Database['public']
